Update notes for submitted changes
* gralloc: Default flexible YUV format to NV21
* Remove sRGB, replace RAW_SENSOR with RAW16 graphics format.
* Fix "error: implicit declaration of function 'free'".
* msm8960: Remove unused variables & functions
* Use standard initializers